package com.tutor.entity;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.tutor.enums.MaterialStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Data
@Table(name = "materials")
public class Material {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JsonIgnoreProperties({
        "materials", "homeworkList", "videos", "createdByAdmin"
    })
    private Teacher teacher;

    @ManyToOne
    @JsonIgnoreProperties({
        "materials","videos"
    })
    private Subject subject;

    @ManyToOne
    @JsonIgnoreProperties({
        "materials", "teachers", "students"
    })
    private Admin admin;

    private String title;
    private String description;
    private String fileUrl;

    @JsonFormat(pattern = "yyyy-MM-dd") // Fix LocalDate deserialization
    private LocalDate uploadedAt;

    @Enumerated(EnumType.STRING)
    @Column(length = 30)
    private MaterialStatus status;

    // Getters and Setters (can also be generated by Lombok @Data)
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }

    public Teacher getTeacher() {
        return teacher;
    }
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public Subject getSubject() {
        return subject;
    }
    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public Admin getAdmin() {
        return admin;
    }
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    public String getFileUrl() {
        return fileUrl;
    }
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public LocalDate getUploadedAt() {
        return uploadedAt;
    }
    public void setUploadedAt(LocalDate uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    public MaterialStatus getStatus() {
        return status;
    }
    public void setStatus(MaterialStatus status) {
        this.status = status;
    }
}
